[project]
name = "planning-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "langchain-core>=0.2.38",
    "langchain-community>=0.2.16",
    "langchain-unstructured>=0.1.2",
    "transformers>=4.44.2",
    "torch>=2.4.1",
    "accelerate>=0.34.0",
    "pillow>=10.4.0",
    "setuptools",
    "flash-attn>=2.6.3",
    "torchvision>=0.19.1",
    "pdf2image>=1.17.0",
]

[tool.uv]
dev-dependencies = [
    "ipdb>=0.13.13",
    "ipython>=8.27.0",
]
